export const ALL_SERVICES = [
  {
    key: 'market',
    labelFr: 'Marché',
    labelEn: 'Market',
    icon: 'storefront-outline',
    color: '#FFD166',
    isBase: true,
  },
  {
    key: 'food',
    labelFr: 'Restauration',
    labelEn: 'Food',
    icon: 'silverware-fork-knife',
    color: '#FF6B6B',
    isBase: true,
  },
  {
    key: 'taxi',
    labelFr: 'Taxi',
    labelEn: 'Taxi',
    icon: 'taxi',
    color: '#2BEE79',
    isBase: true,
  },
  {
    key: 'loba',
    labelFr: 'Loba',
    labelEn: 'Loba',
    icon: 'play-circle',
    color: '#F472B6',
    isBase: true,
  },
  {
    key: 'hotels',
    labelFr: 'Hôtel',
    labelEn: 'Hotels',
    icon: 'bed-queen',
    color: '#60A5FA',
    isBase: true,
  },
  {
    key: 'realestate',
    labelFr: 'Immobilier',
    labelEn: 'Real Estate',
    icon: 'home-city',
    color: '#C084FC',
    isBase: true,
  },
  {
    key: 'flights',
    labelFr: 'Vols',
    labelEn: 'Flights',
    icon: 'airplane',
    color: '#38BDF8',
    isBase: true,
  },
  {
    key: 'betting',
    labelFr: 'Paris Sportifs',
    labelEn: 'Betting',
    icon: 'dice-5',
    color: '#34D399',
    isBase: true,
  },
  {
    key: 'services',
    labelFr: 'Services',
    labelEn: 'Services',
    icon: 'briefcase-variant',
    color: '#FB923C',
    isBase: true,
  },
  {
    key: 'transport',
    labelFr: 'Transport',
    labelEn: 'Transport',
    icon: 'bus',
    color: '#818CF8',
    isBase: true,
  },
  {
    key: 'music',
    labelFr: 'Musique',
    labelEn: 'Music',
    icon: 'headphones',
    color: '#F472B6',
    isBase: true,
  },
  {
    key: 'appartements',
    labelFr: 'Appartements',
    labelEn: 'Apartments',
    icon: 'home-city',
    color: '#C084FC',
    isBase: true,
  },
  {
    key: 'chat',
    labelFr: 'Messages',
    labelEn: 'Chat',
    icon: 'chatbubble-ellipses-outline',
    color: '#2BEE79',
    isBase: true,
  },
  {
    key: 'pharmacy',
    labelFr: 'Pharmacie',
    labelEn: 'Pharmacy',
    icon: 'medical-bag',
    color: '#EF4444',
    isBase: true,
  },
  { 
    key: 'wallet', 
    labelFr: 'Portefeuille', 
    labelEn: 'Wallet', 
    icon: 'wallet', 
    color: '#60A5FA',
    isBase: true,
  },
  { 
    key: 'swap', 
    labelFr: 'Échanger', 
    labelEn: 'Swap', 
    icon: 'swap-horizontal', 
    color: '#F59E0B',
    isBase: true,
  },
  { 
    key: 'delivery', 
    labelFr: 'Livraison', 
    labelEn: 'Delivery', 
    icon: 'truck-delivery', 
    color: '#34D399',
    isBase: true,
  },
  { 
    key: 'streaming', 
    labelFr: 'Streaming', 
    labelEn: 'Streaming', 
    icon: 'movie-open', 
    color: '#F472B6',
    isBase: true,
  },
  { 
    key: 'formation', 
    labelFr: 'Formation', 
    labelEn: 'Education', 
    icon: 'school', 
    color: '#38BDF8',
    isBase: true,
  },
  { 
    key: 'chatbot', 
    labelFr: 'Assistant IA', 
    labelEn: 'Assistant AI', 
    icon: 'robot', 
    color: '#A78BFA',
    isBase: true,
  },
  { 
    key: 'notebook', 
    labelFr: 'Bloc-notes', 
    labelEn: 'Notes', 
    icon: 'notebook-outline', 
    color: '#FBBF24',
    isBase: false,
  },
  { 
    key: 'reservation', 
    labelFr: 'Réservations', 
    labelEn: 'Reservations', 
    icon: 'calendar-check', 
    color: '#F97316',
    isBase: false,
  },
  { 
    key: 'service_perso', 
    labelFr: 'Services Personnels', 
    labelEn: 'Personal Services', 
    icon: 'account-wrench-outline', 
    color: '#60A5FA',
    isBase: false,
  },
  { 
    key: 'service_pro', 
    labelFr: 'Services Pros', 
    labelEn: 'Pro Services', 
    icon: 'briefcase-check-outline', 
    color: '#FB923C',
    isBase: false,
  },
  { 
    key: 'service_digital', 
    labelFr: 'Services Numériques', 
    labelEn: 'Digital Services', 
    icon: 'laptop-mac', 
    color: '#38BDF8',
    isBase: false,
  },
  { 
    key: 'service_maison', 
    labelFr: 'Services Maison', 
    labelEn: 'Home Services', 
    icon: 'home-heart', 
    color: '#F472B6',
    isBase: false,
  },
  { 
    key: 'info_perso', 
    labelFr: 'Infos Personnelles', 
    labelEn: 'Personal Info', 
    icon: 'card-account-details-outline', 
    color: '#94A3B8',
    isBase: false,
  },
  { 
    key: 'dating', 
    labelFr: 'Rencontres', 
    labelEn: 'Dating', 
    icon: 'cards-heart', 
    color: '#F472B6',
    isBase: false,
  },
];
