import { schemaMigrations, createTable, addColumns } from '@nozbe/watermelondb/Schema/migrations'

export default schemaMigrations({
  migrations: [
    {
      toVersion: 10,
      steps: [
        // Add user_id to existing tables that definitely existed (versions 1-9)
        addColumns({ table: 'profiles', columns: [{ name: 'user_id', type: 'string', isIndexed: true }] }),
        addColumns({ table: 'sync_queue', columns: [{ name: 'user_id', type: 'string', isIndexed: true }] }),
        addColumns({ table: 'addresses', columns: [{ name: 'user_id', type: 'string', isIndexed: true }] }),
        addColumns({ table: 'products', columns: [{ name: 'user_id', type: 'string', isIndexed: true }] }),
        addColumns({ table: 'wallet_transactions', columns: [{ name: 'user_id', type: 'string', isIndexed: true }] }),
        addColumns({ table: 'loba_posts', columns: [{ name: 'user_id', type: 'string', isIndexed: true }] }),
        addColumns({ table: 'p2p_transfers', columns: [{ name: 'user_id', type: 'string', isIndexed: true }] }),
        addColumns({ table: 'user_interests', columns: [{ name: 'user_id', type: 'string', isIndexed: true }] }),
        addColumns({ table: 'assistant_messages', columns: [{ name: 'user_id', type: 'string', isIndexed: true }] }),
        addColumns({ table: 'loba_friends', columns: [{ name: 'user_id', type: 'string', isIndexed: true }] }),

        // Create service tables that were added to schema but missing from previous migrations
        createTable({
          name: 'restaurants',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'name', type: 'string' },
            { name: 'cuisine', type: 'string', isIndexed: true },
            { name: 'rating', type: 'number' },
            { name: 'image_url', type: 'string' },
            { name: 'delivery_time', type: 'string' },
            { name: 'price_range', type: 'string' },
            { name: 'address', type: 'string' },
            { name: 'is_open', type: 'boolean' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'hotels',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'name', type: 'string' },
            { name: 'location', type: 'string', isIndexed: true },
            { name: 'stars', type: 'number' },
            { name: 'price_per_night', type: 'string' },
            { name: 'image_url', type: 'string' },
            { name: 'amenities_json', type: 'string' },
            { name: 'rating', type: 'number' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'courses',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'title', type: 'string' },
            { name: 'instructor', type: 'string', isIndexed: true },
            { name: 'price', type: 'string' },
            { name: 'duration', type: 'string' },
            { name: 'image_url', type: 'string' },
            { name: 'category', type: 'string', isIndexed: true },
            { name: 'rating', type: 'number' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'properties',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'title', type: 'string' },
            { name: 'type', type: 'string', isIndexed: true },
            { name: 'price', type: 'string' },
            { name: 'location', type: 'string', isIndexed: true },
            { name: 'bedrooms', type: 'number' },
            { name: 'bathrooms', type: 'number' },
            { name: 'area', type: 'string' },
            { name: 'image_url', type: 'string' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'routes',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'origin', type: 'string', isIndexed: true },
            { name: 'destination', type: 'string', isIndexed: true },
            { name: 'price', type: 'string' },
            { name: 'departure_time', type: 'string' },
            { name: 'carrier', type: 'string' },
            { name: 'type', type: 'string', isIndexed: true },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'taxi_zones',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'name', type: 'string' },
            { name: 'base_fare', type: 'string' },
            { name: 'estimated_wait', type: 'string' },
            { name: 'active_drivers', type: 'number' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'tracks',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'title', type: 'string' },
            { name: 'artist', type: 'string', isIndexed: true },
            { name: 'album', type: 'string' },
            { name: 'duration', type: 'string' },
            { name: 'cover_url', type: 'string' },
            { name: 'stream_url', type: 'string' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'medicaments',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'name', type: 'string', isIndexed: true },
            { name: 'brand', type: 'string' },
            { name: 'price', type: 'string' },
            { name: 'dosage', type: 'string' },
            { name: 'requires_prescription', type: 'boolean' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'videos',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'title', type: 'string' },
            { name: 'channel', type: 'string', isIndexed: true },
            { name: 'views', type: 'string' },
            { name: 'thumbnail_url', type: 'string' },
            { name: 'duration', type: 'string' },
            { name: 'video_url', type: 'string' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'conversations',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'peer_id', type: 'string', isIndexed: true },
            { name: 'last_message', type: 'string' },
            { name: 'last_message_at', type: 'number' },
            { name: 'unread_count', type: 'number' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'dating_profiles',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'name', type: 'string' },
            { name: 'age', type: 'number' },
            { name: 'bio', type: 'string' },
            { name: 'interests_json', type: 'string' },
            { name: 'image_urls_json', type: 'string' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'reservations',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'service_type', type: 'string', isIndexed: true },
            { name: 'service_id', type: 'string', isIndexed: true },
            { name: 'date', type: 'string' },
            { name: 'status', type: 'string', isIndexed: true },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),

        // Create brand new v10 tables
        createTable({
          name: 'betting_matches',
          columns: [
            { name: 'home_team', type: 'string' },
            { name: 'away_team', type: 'string' },
            { name: 'home_logo', type: 'string' },
            { name: 'away_logo', type: 'string' },
            { name: 'score', type: 'string' },
            { name: 'time', type: 'string' },
            { name: 'competition', type: 'string', isIndexed: true },
            { name: 'odds_json', type: 'string' },
            { name: 'start_time', type: 'number' },
            { name: 'status', type: 'string', isIndexed: true },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'betting_bets',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'match_id', type: 'string', isIndexed: true },
            { name: 'selection', type: 'string' },
            { name: 'odds', type: 'number' },
            { name: 'stake', type: 'number' },
            { name: 'status', type: 'string', isIndexed: true },
            { name: 'payout', type: 'number' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'flight_offers',
          columns: [
            { name: 'airline', type: 'string' },
            { name: 'from_city', type: 'string', isIndexed: true },
            { name: 'to_city', type: 'string', isIndexed: true },
            { name: 'departure_time', type: 'number' },
            { name: 'price', type: 'string' },
            { name: 'class', type: 'string' },
            { name: 'status', type: 'string' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'swap_items',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'title', type: 'string' },
            { name: 'description', type: 'string' },
            { name: 'category', type: 'string', isIndexed: true },
            { name: 'condition', type: 'string' },
            { name: 'image_url', type: 'string', isOptional: true },
            { name: 'value_est', type: 'string' },
            { name: 'status', type: 'string', isIndexed: true },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'notebook_notes',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'title', type: 'string' },
            { name: 'content', type: 'string' },
            { name: 'category', type: 'string', isIndexed: true },
            { name: 'color', type: 'string' },
            { name: 'is_pinned', type: 'boolean' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'generic_services',
          columns: [
            { name: 'service_type', type: 'string', isIndexed: true },
            { name: 'name', type: 'string' },
            { name: 'provider_name', type: 'string' },
            { name: 'description', type: 'string' },
            { name: 'price', type: 'string' },
            { name: 'rating', type: 'number' },
            { name: 'location', type: 'string' },
            { name: 'status', type: 'string' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'delivery_orders',
          columns: [
            { name: 'user_id', type: 'string', isIndexed: true },
            { name: 'service_name', type: 'string' },
            { name: 'items_json', type: 'string' },
            { name: 'total_price', type: 'string' },
            { name: 'status', type: 'string', isIndexed: true },
            { name: 'address', type: 'string' },
            { name: 'sync_status', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
      ],
    },
    {
      toVersion: 9,
      steps: [
        addColumns({
          table: 'loba_posts',
          columns: [
            { name: 'thumbnail_path', type: 'string', isOptional: true },
          ],
        }),
        createTable({
          name: 'p2p_transfers',
          columns: [
            { name: 'hash', type: 'string', isIndexed: true },
            { name: 'peer_id', type: 'string' },
            { name: 'direction', type: 'string' },
            { name: 'rail', type: 'string' },
            { name: 'file_size', type: 'number' },
            { name: 'bytes_transferred', type: 'number' },
            { name: 'status', type: 'string', isIndexed: true },
            { name: 'error', type: 'string', isOptional: true },
            { name: 'retry_count', type: 'number' },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
      ],
    },
    {
      toVersion: 8,
      steps: [
        addColumns({
          table: 'loba_posts',
          columns: [
            { name: 'hash', type: 'string', isIndexed: true },
            { name: 'local_media_path', type: 'string', isOptional: true },
            { name: 'category', type: 'string', isIndexed: true },
            { name: 'size', type: 'number' },
            { name: 'is_propagating', type: 'boolean' },
            { name: 'downloaded_at', type: 'number', isOptional: true },
          ],
        }),
        createTable({
          name: 'user_interests',
          columns: [
            { name: 'service', type: 'string', isIndexed: true },
            { name: 'category', type: 'string', isIndexed: true },
            { name: 'weight', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
      ],
    },
    {
      toVersion: 7,
      steps: [
        addColumns({
          table: 'products',
          columns: [
            { name: 'description', type: 'string' },
            { name: 'min_price', type: 'string' },
            { name: 'stock', type: 'number' },
            { name: 'photos_json', type: 'string' },
            { name: 'condition', type: 'string' },
            { name: 'colors_json', type: 'string' },
            { name: 'sizes_json', type: 'string' },
            { name: 'tags_json', type: 'string' },
            { name: 'seller_id', type: 'string', isIndexed: true },
            { name: 'seller_name', type: 'string' },
            { name: 'is_validated', type: 'boolean' },
            { name: 'validated_by', type: 'string', isOptional: true },
            { name: 'product_sync_status', type: 'string', isIndexed: true },
          ],
        }),
      ],
    },
    {
      toVersion: 6,
      steps: [
        addColumns({
          table: 'loba_posts',
          columns: [
            { name: 'filter_color', type: 'string', isOptional: true },
          ],
        }),
      ],
    },
    {
      toVersion: 5,
      steps: [
        createTable({
          name: 'loba_friends',
          columns: [
            { name: 'friend_id', type: 'string', isIndexed: true },
            { name: 'name', type: 'string' },
            { name: 'username', type: 'string', isIndexed: true },
            { name: 'phone', type: 'string', isIndexed: true },
            { name: 'avatar', type: 'string', isOptional: true },
            { name: 'status', type: 'string' },
            { name: 'last_seen', type: 'number' },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
      ],
    },
    {
      toVersion: 4,
      steps: [
        addColumns({
          table: 'addresses',
          columns: [
            { name: 'city', type: 'string', isOptional: true },
            { name: 'city_code', type: 'string', isOptional: true },
          ],
        }),
      ],
    },
    {
      toVersion: 3,
      steps: [
        createTable({
          name: 'products',
          columns: [
            { name: 'name', type: 'string' },
            { name: 'brand', type: 'string' },
            { name: 'price', type: 'string' },
            { name: 'category', type: 'string', isIndexed: true },
            { name: 'is_new', type: 'boolean' },
            { name: 'image_url', type: 'string', isOptional: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'wallet_transactions',
          columns: [
            { name: 'title', type: 'string' },
            { name: 'meta', type: 'string' },
            { name: 'amount', type: 'string' },
            { name: 'is_positive', type: 'boolean' },
            { name: 'wallet_mode', type: 'string', isIndexed: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'loba_posts',
          columns: [
            { name: 'username', type: 'string' },
            { name: 'avatar', type: 'string', isOptional: true },
            { name: 'content', type: 'string' },
            { name: 'image_url', type: 'string', isOptional: true },
            { name: 'video_url', type: 'string', isOptional: true },
            { name: 'likes', type: 'number' },
            { name: 'comments', type: 'number' },
            { name: 'is_liked', type: 'boolean' },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'assistant_messages',
          columns: [
            { name: 'role', type: 'string' },
            { name: 'content', type: 'string' },
            { name: 'created_at', type: 'number' },
          ],
        }),
      ],
    },
    {
      toVersion: 2,
      steps: [
        createTable({
          name: 'addresses',
          columns: [
            { name: 'name', type: 'string' },
            { name: 'full_address', type: 'string', isOptional: true },
            { name: 'latitude', type: 'number' },
            { name: 'longitude', type: 'number' },
            { name: 'unique_id', type: 'string', isIndexed: true },
            { name: 'qr_payload', type: 'string' },
            { name: 'category', type: 'string' },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
      ],
    },
  ],
})
