import { appSchema, tableSchema } from '@nozbe/watermelondb'

export const schema = appSchema({
  version: 9,
  tables: [
    tableSchema({
      name: 'profiles',
      columns: [
        { name: 'phone', type: 'string', isIndexed: true },
        { name: 'device_id', type: 'string' },
        { name: 'public_key', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'kiosk_id', type: 'string', isOptional: true },
        { name: 'verification_token', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sync_queue',
      columns: [
        { name: 'action', type: 'string', isIndexed: true },
        { name: 'payload_json', type: 'string' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'retry_count', type: 'number' },
        { name: 'last_error', type: 'string', isOptional: true },
        { name: 'next_retry_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'signup_nonces',
      columns: [
        { name: 'phone', type: 'string', isIndexed: true },
        { name: 'signup_nonce', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'signup_verifications',
      columns: [
        { name: 'phone', type: 'string', isIndexed: true },
        { name: 'verification_token', type: 'string', isIndexed: true },
        { name: 'channel', type: 'string' },
        { name: 'kiosk_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'addresses',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'category', type: 'string' },
        { name: 'city', type: 'string', isOptional: true },
        { name: 'city_code', type: 'string', isOptional: true },
        { name: 'full_address', type: 'string', isOptional: true },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'unique_id', type: 'string', isIndexed: true },
        { name: 'qr_payload', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'products',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'brand', type: 'string' },
        { name: 'price', type: 'string' },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'is_new', type: 'boolean' },
        { name: 'image_url', type: 'string', isOptional: true },
        { name: 'description', type: 'string' },
        { name: 'min_price', type: 'string' },
        { name: 'stock', type: 'number' },
        { name: 'photos_json', type: 'string' },
        { name: 'condition', type: 'string' },
        { name: 'colors_json', type: 'string' },
        { name: 'sizes_json', type: 'string' },
        { name: 'tags_json', type: 'string' },
        { name: 'seller_id', type: 'string', isIndexed: true },
        { name: 'seller_name', type: 'string' },
        { name: 'is_validated', type: 'boolean' },
        { name: 'validated_by', type: 'string', isOptional: true },
        { name: 'product_sync_status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'wallet_transactions',
      columns: [
        { name: 'title', type: 'string' },
        { name: 'meta', type: 'string' },
        { name: 'amount', type: 'string' },
        { name: 'is_positive', type: 'boolean' },
        { name: 'wallet_mode', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'loba_posts',
      columns: [
        { name: 'username', type: 'string' },
        { name: 'avatar', type: 'string', isOptional: true },
        { name: 'content', type: 'string' },
        { name: 'image_url', type: 'string', isOptional: true },
        { name: 'video_url', type: 'string', isOptional: true },
        { name: 'hash', type: 'string', isIndexed: true },
        { name: 'local_media_path', type: 'string', isOptional: true },
        { name: 'thumbnail_path', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'size', type: 'number' },
        { name: 'likes', type: 'number' },
        { name: 'comments', type: 'number' },
        { name: 'is_liked', type: 'boolean' },
        { name: 'filter_color', type: 'string', isOptional: true },
        { name: 'is_propagating', type: 'boolean' },
        { name: 'downloaded_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'p2p_transfers',
      columns: [
        { name: 'hash', type: 'string', isIndexed: true },
        { name: 'peer_id', type: 'string' },
        { name: 'direction', type: 'string' },
        { name: 'rail', type: 'string' },
        { name: 'file_size', type: 'number' },
        { name: 'bytes_transferred', type: 'number' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'error', type: 'string', isOptional: true },
        { name: 'retry_count', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'user_interests',
      columns: [
        { name: 'service', type: 'string', isIndexed: true },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'weight', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'assistant_messages',
      columns: [
        { name: 'role', type: 'string' },
        { name: 'content', type: 'string' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'loba_friends',
      columns: [
        { name: 'friend_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'username', type: 'string', isIndexed: true },
        { name: 'phone', type: 'string', isIndexed: true },
        { name: 'avatar', type: 'string', isOptional: true },
        { name: 'status', type: 'string' }, // online, mesh, direct, offline
        { name: 'last_seen', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
})
