import { appSchema, tableSchema } from '@nozbe/watermelondb'

export const schema = appSchema({
  version: 9,
  tables: [
    tableSchema({
      name: 'profiles',
      columns: [
        { name: 'phone', type: 'string', isIndexed: true },
        { name: 'device_id', type: 'string' },
        { name: 'public_key', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'kiosk_id', type: 'string', isOptional: true },
        { name: 'verification_token', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sync_queue',
      columns: [
        { name: 'action', type: 'string', isIndexed: true },
        { name: 'payload_json', type: 'string' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'retry_count', type: 'number' },
        { name: 'last_error', type: 'string', isOptional: true },
        { name: 'next_retry_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'signup_nonces',
      columns: [
        { name: 'phone', type: 'string', isIndexed: true },
        { name: 'signup_nonce', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'signup_verifications',
      columns: [
        { name: 'phone', type: 'string', isIndexed: true },
        { name: 'verification_token', type: 'string', isIndexed: true },
        { name: 'channel', type: 'string' },
        { name: 'kiosk_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'addresses',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'category', type: 'string' },
        { name: 'city', type: 'string', isOptional: true },
        { name: 'city_code', type: 'string', isOptional: true },
        { name: 'full_address', type: 'string', isOptional: true },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'unique_id', type: 'string', isIndexed: true },
        { name: 'qr_payload', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'products',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'brand', type: 'string' },
        { name: 'price', type: 'string' },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'is_new', type: 'boolean' },
        { name: 'image_url', type: 'string', isOptional: true },
        { name: 'description', type: 'string' },
        { name: 'min_price', type: 'string' },
        { name: 'stock', type: 'number' },
        { name: 'photos_json', type: 'string' },
        { name: 'condition', type: 'string' },
        { name: 'colors_json', type: 'string' },
        { name: 'sizes_json', type: 'string' },
        { name: 'tags_json', type: 'string' },
        { name: 'seller_id', type: 'string', isIndexed: true },
        { name: 'seller_name', type: 'string' },
        { name: 'is_validated', type: 'boolean' },
        { name: 'validated_by', type: 'string', isOptional: true },
        { name: 'product_sync_status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'wallet_transactions',
      columns: [
        { name: 'title', type: 'string' },
        { name: 'meta', type: 'string' },
        { name: 'amount', type: 'string' },
        { name: 'is_positive', type: 'boolean' },
        { name: 'wallet_mode', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'loba_posts',
      columns: [
        { name: 'username', type: 'string' },
        { name: 'avatar', type: 'string', isOptional: true },
        { name: 'content', type: 'string' },
        { name: 'image_url', type: 'string', isOptional: true },
        { name: 'video_url', type: 'string', isOptional: true },
        { name: 'hash', type: 'string', isIndexed: true },
        { name: 'local_media_path', type: 'string', isOptional: true },
        { name: 'thumbnail_path', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'size', type: 'number' },
        { name: 'likes', type: 'number' },
        { name: 'comments', type: 'number' },
        { name: 'is_liked', type: 'boolean' },
        { name: 'filter_color', type: 'string', isOptional: true },
        { name: 'is_propagating', type: 'boolean' },
        { name: 'downloaded_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'p2p_transfers',
      columns: [
        { name: 'hash', type: 'string', isIndexed: true },
        { name: 'peer_id', type: 'string' },
        { name: 'direction', type: 'string' },
        { name: 'rail', type: 'string' },
        { name: 'file_size', type: 'number' },
        { name: 'bytes_transferred', type: 'number' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'error', type: 'string', isOptional: true },
        { name: 'retry_count', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'user_interests',
      columns: [
        { name: 'service', type: 'string', isIndexed: true },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'weight', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'assistant_messages',
      columns: [
        { name: 'role', type: 'string' },
        { name: 'content', type: 'string' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'loba_friends',
      columns: [
        { name: 'friend_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'username', type: 'string', isIndexed: true },
        { name: 'phone', type: 'string', isIndexed: true },
        { name: 'avatar', type: 'string', isOptional: true },
        { name: 'status', type: 'string' }, // online, mesh, direct, offline
        { name: 'last_seen', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    // Type 1 - Public (sync + P2P shareable)
    tableSchema({
      name: 'restaurants',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'cuisine', type: 'string' },
        { name: 'address', type: 'string' },
        { name: 'city', type: 'string', isIndexed: true },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'rating', type: 'number' },
        { name: 'price_range', type: 'string' },
        { name: 'delivery', type: 'boolean' },
        { name: 'opening_hours', type: 'string' },
        { name: 'photos_json', type: 'string' },
        { name: 'is_validated', type: 'boolean' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'hotels',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'city', type: 'string', isIndexed: true },
        { name: 'address', type: 'string' },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'stars', type: 'number' },
        { name: 'rating', type: 'number' },
        { name: 'price_min', type: 'number' },
        { name: 'price_max', type: 'number' },
        { name: 'amenities_json', type: 'string' },
        { name: 'photos_json', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'is_validated', type: 'boolean' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'courses',
      columns: [
        { name: 'title', type: 'string' },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'instructor', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'duration_hours', type: 'number' },
        { name: 'price', type: 'string' },
        { name: 'level', type: 'string' },
        { name: 'thumbnail_url', type: 'string', isOptional: true },
        { name: 'video_url', type: 'string', isOptional: true },
        { name: 'is_validated', type: 'boolean' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'properties',
      columns: [
        { name: 'title', type: 'string' },
        { name: 'type', type: 'string', isIndexed: true }, // vente, location
        { name: 'category', type: 'string', isIndexed: true }, // appartement, maison, villa
        { name: 'city', type: 'string', isIndexed: true },
        { name: 'address', type: 'string' },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'price', type: 'string' },
        { name: 'surface_m2', type: 'number' },
        { name: 'rooms', type: 'number' },
        { name: 'bedrooms', type: 'number' },
        { name: 'bathrooms', type: 'number' },
        { name: 'photos_json', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'amenities_json', type: 'string' },
        { name: 'seller_id', type: 'string', isIndexed: true },
        { name: 'is_validated', type: 'boolean' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'routes',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'type', type: 'string', isIndexed: true }, // bus, train, metro
        { name: 'city', type: 'string', isIndexed: true },
        { name: 'stops_json', type: 'string' },
        { name: 'schedule_json', type: 'string' },
        { name: 'price', type: 'string' },
        { name: 'operator', type: 'string' },
        { name: 'is_validated', type: 'boolean' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'taxi_zones',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'city', type: 'string', isIndexed: true },
        { name: 'area_coordinates_json', type: 'string' },
        { name: 'price_base', type: 'string' },
        { name: 'price_per_km', type: 'string' },
        { name: 'drivers_count', type: 'number' },
        { name: 'is_validated', type: 'boolean' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'tracks',
      columns: [
        { name: 'title', type: 'string' },
        { name: 'artist', type: 'string' },
        { name: 'album', type: 'string', isOptional: true },
        { name: 'genre', type: 'string', isIndexed: true },
        { name: 'duration_seconds', type: 'number' },
        { name: 'file_path', type: 'string', isOptional: true },
        { name: 'cover_url', type: 'string', isOptional: true },
        { name: 'local_path', type: 'string', isOptional: true },
        { name: 'is_validated', type: 'boolean' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'medicaments',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'generic_name', type: 'string' },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'manufacturer', type: 'string' },
        { name: 'dosage', type: 'string' },
        { name: 'price', type: 'string' },
        { name: 'requires_prescription', type: 'boolean' },
        { name: 'in_stock', type: 'boolean' },
        { name: 'pharmacy_id', type: 'string', isIndexed: true },
        { name: 'description', type: 'string' },
        { name: 'is_validated', type: 'boolean' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'videos',
      columns: [
        { name: 'title', type: 'string' },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'genre', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'duration_seconds', type: 'number' },
        { name: 'thumbnail_url', type: 'string', isOptional: true },
        { name: 'video_url', type: 'string', isOptional: true },
        { name: 'local_path', type: 'string', isOptional: true },
        { name: 'is_validated', type: 'boolean' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    // Type 2 - Personal (sync, not shareable)
    tableSchema({
      name: 'conversations',
      columns: [
        { name: 'participant_id', type: 'string', isIndexed: true },
        { name: 'participant_name', type: 'string' },
        { name: 'last_message', type: 'string' },
        { name: 'last_message_at', type: 'number' },
        { name: 'unread_count', type: 'number' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'dating_profiles',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'age', type: 'number' },
        { name: 'gender', type: 'string' },
        { name: 'city', type: 'string' },
        { name: 'bio', type: 'string' },
        { name: 'photos_json', type: 'string' },
        { name: 'interests_json', type: 'string' },
        { name: 'preferences_json', type: 'string' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'reservations',
      columns: [
        { name: 'service_type', type: 'string', isIndexed: true }, // restaurant, hotel, flight
        { name: 'service_id', type: 'string', isIndexed: true },
        { name: 'service_name', type: 'string' },
        { name: 'date', type: 'number' },
        { name: 'time', type: 'string' },
        { name: 'status', type: 'string' }, // pending, confirmed, cancelled
        { name: 'details_json', type: 'string' },
        { name: 'total_price', type: 'string' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
})
